version: "3.8"

services:
  main-db:
    container_name: main-db
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    volumes:
      - main-db-data:/var/lib/postgresql/data

volumes:
  main-db-data:
    driver: local
